package config

import (
	"os"
	"strings"
	"testing"
)

func TestLoadConfig(t *testing.T) {
	// Create a config.yaml file in the current directory for the test
	content := `
sources:
  - type: github
    url: https://github.com/test-org/test-repo
    path: docs/adrs
    auth:
      token: test-token
`
	configFileName := "config.yaml"
	if err := os.WriteFile(configFileName, []byte(content), 0644); err != nil {
		t.Fatalf("Failed to write temp config file: %v", err)
	}
	defer func() {
		if err := os.Remove(configFileName); err != nil {
			t.Logf("failed to remove temporary config file: %v", err)
		}
	}()

	cfg, err := LoadConfig()
	if err != nil {
		t.Fatalf("LoadConfig() failed: %v", err)
	}

	if len(cfg.Sources) != 1 {
		t.Fatalf("expected 1 source, got %d", len(cfg.Sources))
	}

	source := cfg.Sources[0]
	if source.Type != "github" {
		t.Errorf("expected source type 'github', got %q", source.Type)
	}
	if source.URL != "https://github.com/test-org/test-repo" {
		t.Errorf("expected source URL 'https://github.com/test-org/test-repo', got %q", source.URL)
	}
}

func TestEnsureUniqueSourceNames_AutoGeneratedNames(t *testing.T) {
	cfg := &Config{
		Sources: []Source{
			{Type: "github", URL: "https://github.com/org1/repo1"},
			{Type: "gitlab", URL: "https://gitlab.com/org2/repo2"},
			{Type: "github", URL: "https://github.com/org3/repo3"},
		},
	}

	err := cfg.ensureUniqueSourceNames()
	if err != nil {
		t.Fatalf("ensureUniqueSourceNames() failed: %v", err)
	}

	// Verify auto-generated names are in the correct format
	expectedNames := []string{"github-0", "gitlab-0", "github-1"}
	for i, expected := range expectedNames {
		if cfg.Sources[i].Name != expected {
			t.Errorf("source[%d]: expected name %q, got %q", i, expected, cfg.Sources[i].Name)
		}
	}
}

func TestEnsureUniqueSourceNames_DuplicateDetection(t *testing.T) {
	cfg := &Config{
		Sources: []Source{
			{Name: "my-source", Type: "github", URL: "https://github.com/org1/repo1"},
			{Name: "my-source", Type: "gitlab", URL: "https://gitlab.com/org2/repo2"},
		},
	}

	err := cfg.ensureUniqueSourceNames()
	if err == nil {
		t.Fatal("expected error for duplicate source names, got nil")
	}

	expectedError := "duplicate source name: my-source"
	if err.Error() != expectedError {
		t.Errorf("expected error %q, got %q", expectedError, err.Error())
	}
}

func TestEnsureUniqueSourceNames_CounterIncrement(t *testing.T) {
	cfg := &Config{
		Sources: []Source{
			{Type: "github", URL: "https://github.com/org1/repo1"},
			{Type: "github", URL: "https://github.com/org2/repo2"},
			{Type: "github", URL: "https://github.com/org3/repo3"},
			{Type: "gitlab", URL: "https://gitlab.com/org4/repo4"},
			{Type: "gitlab", URL: "https://gitlab.com/org5/repo5"},
		},
	}

	err := cfg.ensureUniqueSourceNames()
	if err != nil {
		t.Fatalf("ensureUniqueSourceNames() failed: %v", err)
	}

	// Verify counter increments correctly for each type
	expectedNames := []string{"github-0", "github-1", "github-2", "gitlab-0", "gitlab-1"}
	for i, expected := range expectedNames {
		if cfg.Sources[i].Name != expected {
			t.Errorf("source[%d]: expected name %q, got %q", i, expected, cfg.Sources[i].Name)
		}
	}
}

func TestEnsureUniqueSourceNames_PreserveManualNames(t *testing.T) {
	cfg := &Config{
		Sources: []Source{
			{Name: "custom-name-1", Type: "github", URL: "https://github.com/org1/repo1"},
			{Type: "github", URL: "https://github.com/org2/repo2"},
			{Name: "custom-name-2", Type: "gitlab", URL: "https://gitlab.com/org3/repo3"},
			{Type: "gitlab", URL: "https://gitlab.com/org4/repo4"},
		},
	}

	err := cfg.ensureUniqueSourceNames()
	if err != nil {
		t.Fatalf("ensureUniqueSourceNames() failed: %v", err)
	}

	// Verify manually specified names are preserved
	expectedNames := []string{"custom-name-1", "github-0", "custom-name-2", "gitlab-0"}
	for i, expected := range expectedNames {
		if cfg.Sources[i].Name != expected {
			t.Errorf("source[%d]: expected name %q, got %q", i, expected, cfg.Sources[i].Name)
		}
	}
}

func TestEnsureUniqueSourceNames_AvoidCollisions(t *testing.T) {
	// Test that auto-generated names avoid collisions with manually specified names
	cfg := &Config{
		Sources: []Source{
			{Name: "github-0", Type: "github", URL: "https://github.com/org1/repo1"},
			{Type: "github", URL: "https://github.com/org2/repo2"}, // Should become github-1
			{Name: "github-2", Type: "github", URL: "https://github.com/org3/repo3"},
			{Type: "github", URL: "https://github.com/org4/repo4"}, // Should become github-3 (skips github-2 which is manually specified)
		},
	}

	err := cfg.ensureUniqueSourceNames()
	if err != nil {
		t.Fatalf("ensureUniqueSourceNames() failed: %v", err)
	}

	// Verify all names are unique
	seenNames := make(map[string]bool)
	for i, source := range cfg.Sources {
		if seenNames[source.Name] {
			t.Errorf("source[%d]: duplicate name %q", i, source.Name)
		}
		seenNames[source.Name] = true
	}

	// Verify manually specified names are preserved and auto-generated names avoid collisions
	expectedNames := []string{"github-0", "github-1", "github-2", "github-3"}
	for i, expected := range expectedNames {
		if cfg.Sources[i].Name != expected {
			t.Errorf("source[%d]: expected name %q, got %q", i, expected, cfg.Sources[i].Name)
		}
	}
}

func TestValidateAndNormalizeSources_DuplicateURL(t *testing.T) {
	cfg := &Config{
		Sources: []Source{
			{Name: "source-1", Type: "github", URL: "https://github.com/test-org/test-repo"},
			{Name: "source-2", Type: "github", URL: "https://github.com/test-org/test-repo"},
		},
	}

	err := cfg.validateAndNormalizeSources()
	if err == nil {
		t.Fatal("expected error for duplicate source URLs, got nil")
	}

	// Check that error message mentions both the URL and the conflicting sources
	errMsg := err.Error()
	if !contains(errMsg, "duplicate source URL") {
		t.Errorf("error message should mention 'duplicate source URL', got: %q", errMsg)
	}
	if !contains(errMsg, "https://github.com/test-org/test-repo") {
		t.Errorf("error message should mention the duplicate URL, got: %q", errMsg)
	}
	if !contains(errMsg, "source-1") {
		t.Errorf("error message should mention 'source-1', got: %q", errMsg)
	}
}

func TestValidateAndNormalizeSources_DuplicateURLWithAutoGeneratedName(t *testing.T) {
	cfg := &Config{
		Sources: []Source{
			{Type: "github", URL: "https://github.com/test-org/test-repo"},
			{Type: "gitlab", URL: "https://github.com/test-org/test-repo"}, // Same URL, different type
		},
	}

	err := cfg.validateAndNormalizeSources()
	if err == nil {
		t.Fatal("expected error for duplicate source URLs, got nil")
	}

	errMsg := err.Error()
	if !contains(errMsg, "duplicate source URL") {
		t.Errorf("error message should mention 'duplicate source URL', got: %q", errMsg)
	}
	// First source gets auto-generated name "github-0"
	if !contains(errMsg, "github-0") {
		t.Errorf("error message should mention the auto-generated name 'github-0' for the first source, got: %q", errMsg)
	}
	// Second source should be identified by type and index
	if !contains(errMsg, "gitlab") && !contains(errMsg, "index: 1") {
		t.Errorf("error message should mention the second source's type 'gitlab' or 'index: 1', got: %q", errMsg)
	}
}

func TestValidateAndNormalizeSources_UniqueURLsAllowed(t *testing.T) {
	cfg := &Config{
		Sources: []Source{
			{Name: "source-1", Type: "github", URL: "https://github.com/org1/repo1"},
			{Name: "source-2", Type: "github", URL: "https://github.com/org2/repo2"},
			{Name: "source-3", Type: "gitlab", URL: "https://gitlab.com/org3/repo3"},
		},
	}

	err := cfg.validateAndNormalizeSources()
	if err != nil {
		t.Fatalf("validateAndNormalizeSources() should not fail with unique URLs: %v", err)
	}
}

// contains checks if a string contains a substring
func contains(s, substr string) bool {
	return strings.Contains(s, substr)
}
